#<compute shader>

#version 460 core
#define id gl_GlobalInvocationID
layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout (RGBA32F, binding = 0) uniform image2D source_float_texture;
layout (R32UI, binding = 1) uniform uimage2D target_int_texture;

const float int_texture_max_value = 65535;

void main(){
	imageStore(target_int_texture, ivec2(id.xy), uvec4(float(imageLoad(source_float_texture, ivec2(id.xy)) * int_texture_max_value)));
}